name: Golang CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        golang-version: ['1.2', '1.18', '1.20']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Golang
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.golang-version }}
    - name: Run tests
      run: go test
